title: Simon Bakken-Jantasuk
author:
  name: Simon-Bakken-Jantasuk
  email: simonbakkenjantasuk@pm.me
description: >- 
  En blog som handler seg om Linux, programvarer, matematikk og programmering. I andre ord– en veldig based blog.

minima:
  skin: auto 
  social_links:
    - { platform: github,  user_url: "https://github.com/Simon-Bakken-Jantasuk" }
    - { platform: stackoverflow, user_url: "https://stackoverflow.com/users/20717655/simon-bakken-jantasuk" }
    - { platform: instagram, user_url: "https://www.instagram.com/bakkenjantasuk/"}

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

remote_theme: jekyll/minima

markdown: kramdown

kramdown:
  math_engine: katex 


disqus:
  shortname: simonbakkenjantasuk

domain: simonbakkenjantasuk.xyz       
url: https://simonbakkenjantasuk.xyz

repository: Simon-Bakken-Jantasuk/simon-bakken-jantasuk.github.io
